<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title ?? $appName }}</title>
    <style>
        :root{--surface:#fff;--surface-soft:#eef4fb;--text:#17324d;--muted:#67809a;--line:#d7e2ee;--blue:#1f6fb2;--blue-deep:#184f82;--green:#1f9d7a;--orange:#ee8d2d;--danger:#d9534f;--shadow:0 24px 60px rgba(24,58,93,.12);--sidebar-width:284px;--topbar-height:78px}
        *{box-sizing:border-box} html{scroll-behavior:smooth} body{margin:0;font-family:Poppins,Inter,"Segoe UI",sans-serif;color:var(--text);background:radial-gradient(circle at top left,rgba(31,111,178,.12),transparent 26%),radial-gradient(circle at top right,rgba(31,157,122,.10),transparent 24%),linear-gradient(180deg,#f7fbff 0%,#f3f6fa 45%,#eef3f8 100%)} a{color:inherit;text-decoration:none} button,input,select,textarea{font:inherit}
        .app-shell{display:grid;grid-template-columns:var(--sidebar-width) minmax(0,1fr);min-height:100vh}.sidebar{position:sticky;top:0;height:100vh;padding:28px 22px;background:linear-gradient(180deg,#0f3356 0%,#174d7c 52%,#1f6fb2 100%);color:#eff7ff;box-shadow:inset -1px 0 0 rgba(255,255,255,.08);z-index:20}.brand{display:flex;align-items:center;gap:14px;margin-bottom:28px}.brand-mark{width:52px;height:52px;display:grid;place-items:center;border-radius:16px;background:linear-gradient(135deg,rgba(255,255,255,.20),rgba(255,255,255,.08));border:1px solid rgba(255,255,255,.12);backdrop-filter:blur(8px)}.brand p,.sidebar-note,.nav-label,.status-note{color:rgba(239,247,255,.76)}.brand h1{margin:0;font-size:1rem;line-height:1.3;font-weight:700}.brand p{margin:4px 0 0;font-size:.82rem}.sidebar-note{margin:0 0 18px;padding:14px 16px;border-radius:16px;background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.10);font-size:.88rem;line-height:1.6}.nav-label{display:block;margin:18px 10px 12px;font-size:.74rem;font-weight:600;letter-spacing:.08em;text-transform:uppercase}.menu{display:grid;gap:8px}.menu-link{display:flex;align-items:center;gap:14px;padding:12px 14px;border-radius:16px;transition:transform .2s ease,background .2s ease}.menu-link:hover,.menu-link.active{background:rgba(255,255,255,.12);transform:translateX(4px)}.menu-link span:last-child{color:#f5fbff;font-size:.94rem;font-weight:500}.menu-icon,.section-icon,.stat-icon,.chip-icon{width:20px;height:20px;flex:0 0 20px}.sidebar-footer{position:absolute;right:22px;bottom:22px;left:22px;display:grid;gap:12px}.status-card,.logout-button{border-radius:18px;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.10)}.status-card{padding:14px 16px}.status-card strong{display:block;margin-bottom:6px;font-size:.92rem}.status-note{margin:0;font-size:.82rem;line-height:1.5}.logout-button{display:flex;align-items:center;justify-content:center;gap:10px;padding:12px 14px;color:#fff;cursor:pointer}
        .main-content{min-width:0}.topbar{position:sticky;top:0;z-index:15;display:flex;align-items:center;justify-content:space-between;gap:18px;min-height:var(--topbar-height);padding:18px 28px;background:rgba(244,247,251,.86);backdrop-filter:blur(12px);border-bottom:1px solid rgba(23,50,77,.06)}.topbar-left,.topbar-right{display:flex;align-items:center;gap:14px}.sidebar-toggle{display:none;width:44px;height:44px;border:none;border-radius:14px;background:var(--surface);box-shadow:0 10px 24px rgba(23,50,77,.08);color:var(--blue);cursor:pointer}.page-title h2{margin:0;font-size:1.35rem;font-weight:700}.page-title p{margin:4px 0 0;color:var(--muted);font-size:.92rem}.toolbar-search{display:flex;align-items:center;gap:10px;width:min(420px,100%);padding:12px 16px;border-radius:16px;background:var(--surface);border:1px solid rgba(31,111,178,.08);box-shadow:0 14px 30px rgba(23,50,77,.06)}.toolbar-search input{width:100%;border:none;outline:none;background:transparent;color:var(--text)}
        .status-pill,.badge,.mini-badge{display:inline-flex;align-items:center;gap:8px;border-radius:999px;font-size:.82rem;font-weight:600}.status-pill{padding:10px 14px;background:rgba(31,157,122,.10);color:#117658}.user-chip{display:flex;align-items:center;gap:12px;padding:8px 10px 8px 8px;border-radius:18px;background:var(--surface);box-shadow:0 14px 30px rgba(23,50,77,.06)}.avatar{width:42px;height:42px;display:grid;place-items:center;border-radius:14px;background:linear-gradient(135deg,var(--blue),var(--green));color:#fff;font-weight:700}.user-chip strong{display:block;font-size:.92rem}.user-chip small{color:var(--muted);font-size:.78rem}.page-body{padding:18px 28px 32px}.hero-panel{position:relative;overflow:hidden;display:grid;grid-template-columns:1.3fr .9fr;gap:24px;padding:28px;border-radius:30px;background:linear-gradient(135deg,rgba(15,51,86,.96),rgba(31,111,178,.94)),linear-gradient(135deg,rgba(31,157,122,.10),transparent);box-shadow:var(--shadow);color:#fff}.hero-panel::after{content:"";position:absolute;right:-80px;bottom:-80px;width:260px;height:260px;border-radius:40px;background:linear-gradient(135deg,rgba(238,141,45,.22),rgba(255,255,255,.04));transform:rotate(24deg)}
        .eyebrow,.hero-copy p,.hero-meta,.highlight-card p{color:rgba(255,255,255,.78)}.eyebrow{display:inline-flex;align-items:center;gap:8px;padding:8px 12px;border-radius:999px;background:rgba(255,255,255,.12);font-size:.8rem;font-weight:600}.hero-copy h3{margin:18px 0 12px;font-size:clamp(1.8rem,3vw,2.8rem);line-height:1.15}.hero-copy p{max-width:680px;margin:0;font-size:.96rem;line-height:1.8}.hero-meta{display:flex;flex-wrap:wrap;gap:18px;margin-top:22px}.hero-meta strong,.highlight-card strong{display:block;color:#fff;font-size:1.05rem}.hero-meta span,.highlight-card p{font-size:.82rem;line-height:1.6}.hero-side{position:relative;z-index:1;display:grid;gap:16px;align-content:start}.highlight-card{padding:18px 20px;border-radius:22px;background:rgba(255,255,255,.11);border:1px solid rgba(255,255,255,.10);backdrop-filter:blur(12px)}.highlight-head,.section-head,.table-toolbar,.split-header,.setting-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.highlight-head{margin-bottom:14px}.mini-badge{padding:7px 10px;color:#fff3e4;background:rgba(238,141,45,.24)}
        .dashboard-grid,.content-grid,.triple-grid,.double-grid{display:grid;gap:22px;margin-top:24px}.dashboard-grid{grid-template-columns:repeat(4,minmax(0,1fr))}.content-grid{grid-template-columns:minmax(0,1.55fr) minmax(320px,.95fr);align-items:start}.double-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.triple-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.stat-card,.panel,.list-item,.timeline-item,.setting-card{background:var(--surface);border:1px solid rgba(23,50,77,.06);box-shadow:0 18px 40px rgba(23,50,77,.06)}.stat-card{padding:20px;border-radius:24px}.stat-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.stat-icon-wrap,.section-icon-wrap{display:grid;place-items:center;border-radius:16px}.stat-icon-wrap{width:46px;height:46px;background:var(--surface-soft);color:var(--blue)}.tone-green{color:var(--green)!important;background:rgba(31,157,122,.10)!important}.tone-orange{color:var(--orange)!important;background:rgba(238,141,45,.10)!important}.tone-deep{color:var(--blue-deep)!important;background:rgba(24,79,130,.10)!important}.stat-card h4,.panel h4{margin:0;font-size:.96rem}.stat-card strong{display:block;margin:16px 0 8px;font-size:2rem;line-height:1}.metric-note{margin:0;color:var(--muted);font-size:.84rem;line-height:1.6}.panel{border-radius:28px;padding:24px}.section-tag{display:inline-flex;align-items:center;gap:8px;padding:8px 12px;border-radius:999px;background:rgba(31,111,178,.08);color:var(--blue);font-size:.8rem;font-weight:700}.section-head{margin-bottom:18px}.section-head h3,.split-header h3,.setting-head h3{margin:0;font-size:1.08rem}.section-intro,.split-header p,.setting-copy p,.table-toolbar p{margin:6px 0 0;color:var(--muted);font-size:.9rem;line-height:1.6}.badge{padding:8px 12px;background:rgba(23,50,77,.06);color:var(--text)}.table-toolbar{margin:20px 0 16px}.filters{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;margin-bottom:16px}.control,.step-card,.doc-card,.report-card{border-radius:16px;border:1px solid var(--line);background:#fbfdff}.control{padding:12px 14px;outline:none;color:var(--text)}
        table{width:100%;border-collapse:collapse} th,td{padding:14px 10px;text-align:left;border-bottom:1px solid rgba(23,50,77,.08);vertical-align:top;font-size:.9rem} th{color:var(--muted);font-size:.78rem;text-transform:uppercase;letter-spacing:.05em;font-weight:700} tbody tr:hover{background:rgba(31,111,178,.03)} .table-meta{color:var(--muted);font-size:.82rem}.badge.success,.mini-badge.success{background:rgba(31,157,122,.12);color:#117658}.badge.warn,.mini-badge.warn{background:rgba(238,141,45,.16);color:#aa5d10}.badge.danger,.mini-badge.danger{background:rgba(217,83,79,.12);color:#b3423f}.list-group,.timeline,.settings-grid{display:grid;gap:14px}.list-item,.timeline-item,.setting-card{padding:18px;border-radius:20px}.list-item strong,.timeline-item strong,.setting-card strong,.doc-card strong,.report-card strong,.step-card strong{display:block;margin-bottom:6px;font-size:.95rem}.list-item p,.timeline-item p,.setting-card p,.doc-card p,.report-card p,.step-card p{margin:0;color:var(--muted);font-size:.86rem;line-height:1.6}.split{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(0,.85fr);gap:18px}.step-grid,.doc-grid,.report-grid{display:grid;gap:14px;margin-top:18px}.step-grid{grid-template-columns:repeat(4,minmax(0,1fr))}.doc-grid,.report-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.step-card,.doc-card,.report-card{padding:18px}.step-card.active{border-color:rgba(31,111,178,.28);background:linear-gradient(180deg,rgba(31,111,178,.08),rgba(31,157,122,.05))}
        .step-index{display:inline-flex;align-items:center;justify-content:center;width:34px;height:34px;margin-bottom:12px;border-radius:12px;background:rgba(31,111,178,.12);color:var(--blue);font-weight:700}.subtle-box{margin-top:18px;padding:18px;border-radius:18px;background:linear-gradient(180deg,#f9fbfd 0%,#eef5fb 100%);border:1px dashed rgba(31,111,178,.24)}.subtle-box h4{margin:0 0 10px;font-size:.96rem}.subtle-box ul{margin:0;padding-left:18px;color:var(--muted);line-height:1.8;font-size:.88rem}.timeline-item{display:grid;grid-template-columns:54px minmax(0,1fr);gap:14px;align-items:start}.timeline-mark{width:54px;height:54px;display:grid;place-items:center;border-radius:16px;background:linear-gradient(135deg,rgba(31,111,178,.14),rgba(31,157,122,.14));color:var(--blue)}.timeline-meta{margin-top:8px;color:var(--muted);font-size:.78rem}.report-card{background:linear-gradient(180deg,#fff 0%,#f6fbff 100%)}.setting-card{display:flex;gap:16px;align-items:flex-start}.section-anchor{scroll-margin-top:98px}.footer{margin-top:24px;padding:22px 8px 0;color:var(--muted);font-size:.86rem}.footer strong{color:var(--text)}.overlay{display:none}
        @media (max-width:1240px){.dashboard-grid,.step-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.content-grid,.split,.double-grid,.doc-grid,.report-grid,.triple-grid,.hero-panel{grid-template-columns:1fr}.filters{grid-template-columns:repeat(2,minmax(0,1fr))}}
        @media (max-width:980px){.app-shell{grid-template-columns:1fr}.sidebar{position:fixed;inset:0 auto 0 0;width:min(86vw,320px);transform:translateX(-100%);transition:transform .28s ease}.sidebar.open{transform:translateX(0)}.sidebar-toggle,.overlay.visible{display:inline-grid}.overlay.visible{position:fixed;inset:0;background:rgba(7,21,34,.42);z-index:18}.topbar{padding:18px 20px}.page-body{padding:14px 20px 28px}.topbar,.topbar-right{flex-wrap:wrap}.toolbar-search{width:100%}}
        @media (max-width:640px){.dashboard-grid,.filters,.step-grid,.doc-grid,.report-grid,.triple-grid{grid-template-columns:1fr}.hero-panel,.panel,.stat-card{padding:20px;border-radius:22px}.topbar{min-height:auto}.page-title h2{font-size:1.1rem}.user-chip{width:100%;justify-content:space-between}th:nth-child(4),td:nth-child(4),th:nth-child(6),td:nth-child(6){display:none}}
    </style>
</head>
<body>
    <div class="overlay" id="overlay"></div>
    <div class="app-shell">
        @include('partials.sidebar')
        <main class="main-content">
            @include('partials.topbar')
            <div class="page-body">
                @yield('content')
                <footer class="footer">
                    <strong>{{ $appName }}</strong> • Fondasi antarmuka Laravel untuk Sistem Informasi Pendataan Pengungsi • 2026 • Rumah Detensi Imigrasi Surabaya
                </footer>
            </div>
        </main>
    </div>

    <script>
        const sidebar = document.getElementById('sidebar');
        const overlay = document.getElementById('overlay');
        const sidebarToggle = document.getElementById('sidebarToggle');

        const toggleSidebar = (open) => {
            sidebar.classList.toggle('open', open);
            overlay.classList.toggle('visible', open);
        };

        sidebarToggle?.addEventListener('click', () => toggleSidebar(true));
        overlay?.addEventListener('click', () => toggleSidebar(false));
        document.querySelectorAll('.menu-link').forEach((link) => {
            link.addEventListener('click', () => {
                if (window.innerWidth <= 980) toggleSidebar(false);
            });
        });
    </script>
</body>
</html>
